config/routes.rb
MarcosWeb::Application.routes.draw do
  root to: 'home#index'

  resources :proyects, only: [:index]
  resources :contacts, only: [:index,:create]
  resources :abouts, only: [:index]
  resources :blogs, only: [:index,:show] do
    resources :comments, only: [:create]
  end

  devise_for :users,skip: [:registrations,:passwords], path: "auth",
      path_names:
      { sign_in: 'login', sign_out: 'logout', password: 'secret',
        confirmation: 'verification', unlock: 'unblock',
        registration: 'register', sign_up: 'cmon_let_me_in'
      }
  as :user do
    get 'admin/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'admin/users' => 'devise/registrations#update', :as => 'user_registration'
  end



  namespace :admin do
    match 'home' =>'home#index',as: 'home', via: [:get]
    resources :proyects ,except: [:show] do
      resources :pphotos, only: [:create, :destroy]
    end
    resources :posts,except: [:show] do
      collection do
        post 'search' => 'posts#search', as: 'search'
        get 'sort/:by' => 'posts#sort', as: 'sort'
      end
    end
    resources :cvs,only: [:edit, :update]
    resources :comments,except: [:show, :new,:create] do
      collection do
        post 'search' => 'comments#search', as: 'search'
      end
    end


  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Humanizer
  require_human_on :create
  # Es posible crear comentarios para cualquier objeto
  attr_accessible :body, :email, :user,:humanizer_answer,:humanizer_question_id
  validates_presence_of :body, :email,:user
  validates_format_of :email, with: /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i
  belongs_to :commentable, polymorphic: true

  #replicas a los comentarios desactivados en modelo y migracion
  #has_many :replies, class_name: :Comment, foreign_key: :replied_of_id, dependent: :destroy

  extend FriendlyId
  friendly_id :id, use: :slugged

  PAGE_INDEX=20
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  authorize_resource class: false

  def index
    @comments=Comment.paginate(page: params[:page], per_page: Comment::PAGE_INDEX)
    respond_to do |format|
      format.html
      format.json { render json: @comments }
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @load_javascript="run_rich_text_editor('es-ES');"
  end

  def update
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to admin_comments_path, notice: t('activerecord.attributes.comment.update') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:alert]= t('activerecord.attributes.comment.remove')
    respond_to do |format|
      format.html { redirect_to  admin_comments_path  }
      format.json { head :no_content }
    end
  end

  def search
    @comments = Comment.paginate conditions: ['user LIKE ? and body LIKE ?',
                                          "%#{params[:search][:user]}%",
                                          "%#{params[:search][:body]}%"],
                             page: params[:page],
                             order: 'created_at desc',
                             per_page: Comment::PAGE_INDEX
    render "index"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(params[:comment])
    #de momento solo tendre comentarios para Blog
    @comment.commentable_id = Post.find_by_slug(params[:blog_id]).id
    @comment.commentable_type = 'Post'
    @message = Message.new(name: @comment.user,
                           surname: '_',
                           email: @comment.email,
                           subject: @url+'blogs/'+@comment.commentable.slug,
                           body: @comment.body,
                           phone: '_')
    respond_to do |format|
      if @comment.save
        CommentNotifier.contact_me(@message).deliver
        session[:post]=''
        format.html { redirect_to :back, notice: t('activerecord.attributes.comment.create') }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        errors = humanize_errors_html(@comment.errors)
        session[:post]=@comment.body
        format.html { redirect_to :back, alert: t('activerecord.attributes.comment.fail')+errors }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/views/admin/comments/_edit_form.html.erb
<%= form_for(@comment,url: admin_comment_path,html: { multipart: true }) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> <%=t('common.errors_form_wrapper')%>:</h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-xs-4 col-md-4">
      <div class="form-group">
        <%=f.label :user%>
        <%=f.text_field :user, class: 'form-control'%>
      </div>
    </div>
    <div class="col-xs-4 col-md-4">
      <div class="form-group">
        <%=f.label :email%>
        <%=f.text_field :email, class: 'form-control'%>
      </div>
    </div>

  </div>


  <div class="form-group">
    <%=f.label :body%>
    <%=f.text_area :body,size: '30x10' ,class: 'wysihtml5 form-control '%>
  </div>

  <%= f.submit  t('common.edit'), class: 'btn btn-primary' %>

<%end%>

app/views/admin/comments/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h3 class="form-title form-title-first"><i class="icon-terminal"></i> <%=t('admin_zone.comment.edit')+@comment.user%></h3>
    <div class="widget">
      <div class="widget-content-white glossed">
        <div class="padded">
          <%= render 'edit_form' %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= link_to t('admin_zone.comment.back'), admin_comments_path, class: 'btn btn-default' %>

app/views/admin/comments/index.html.erb
<h3 class="section-title more-margin"><i class="icon-comment-alt"></i> <%=t('admin_zone.comment.list')%></h3>
<div class="row">
  <div class="col-xs-3 col-md-3">
    <%=link_to t('admin_zone.global.title'), admin_home_path  %>
  </div>
  <div class="col-xs-9 col-md-9">
    <%= form_for(:search,url: search_admin_comments_path,method: 'post',class: 'form-inline') do |f| %>
      <div class="col-xs-12 col-md-5">
      <%=f.text_field :user,placeholder: t('activerecord.attributes.comment.user'),class: 'form-control'%>
      </div>
      <div class="col-xs-12 col-md-5">
      <%=f.text_field :body,placeholder: t('activerecord.attributes.comment.body'),class: 'form-control'%>
      </div>
      <div class="col-xs-12 col-md-2">
      <%= f.submit  t('common.search'), class: 'btn btn-primary' %>
      </div>
    <%end%>
  </div>
</div>
<div class="padded">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th><%=t('admin_zone.comment.body')%></th>
      <th><%=t('admin_zone.comment.tipo')%></th>
      <th><%=t('admin_zone.comment.user')%></th>
      <th><%=t('admin_zone.comment.email')%></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%=
             comment.body.length > 20?
                     comment.body[0..20].html_safe+' ...' : comment.body.html_safe
            %>
         </td>
        <td><%=comment.commentable_type%> (<%=comment.commentable.slug%>)</td>
        <td><%=comment.user%></td>
        <td><%=comment.email%></td>

        <td class="text-right">
          <a class="btn btn-default btn-xs" href="<%=edit_admin_comment_path(comment)%>"><i class="icon-pencil"></i> edit</a>
          <a class="btn btn-danger btn-xs" data-method="delete" href="<%=admin_comment_path(comment)%>"><i class="icon-remove"></i></a>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate @comments, previous_label: t('will_paginate.previous_label'), next_label: t('will_paginate.next_label'),
                    page_gap: t('will_paginate.page_gap'),class: 'pagination pagination-large pagination-centered'%>
</div>