config/routes.rb
MarcosWeb::Application.routes.draw do
  root to: 'home#index'

  resources :proyects, only: [:index]
  resources :contacts, only: [:index,:create]
  resources :abouts, only: [:index]
  resources :blogs, only: [:index,:show] do
    resources :comments, only: [:create]
  end

  devise_for :users,skip: [:registrations,:passwords], path: "auth",
      path_names:
      { sign_in: 'login', sign_out: 'logout', password: 'secret',
        confirmation: 'verification', unlock: 'unblock',
        registration: 'register', sign_up: 'cmon_let_me_in'
      }
  as :user do
    get 'admin/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'admin/users' => 'devise/registrations#update', :as => 'user_registration'
  end



  namespace :admin do
    match 'home' =>'home#index',as: 'home', via: [:get]
    resources :proyects ,except: [:show] do
      resources :pphotos, only: [:create, :destroy]
    end
    resources :posts,except: [:show] do
      collection do
        post 'search' => 'posts#search', as: 'search'
        get 'sort/:by' => 'posts#sort', as: 'sort'
      end
    end
    resources :cvs,only: [:edit, :update]
    resources :comments,except: [:show, :new,:create] do
      collection do
        post 'search' => 'comments#search', as: 'search'
      end
    end


  end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  authorize_resource class: false

  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :load_meta
  def index
    @carrusel=Proyect.order("RAND()").first(5)
    @load_javascript='start_carrousel();'
  end

  private
  def load_meta
    @web_title= t('home.title')
    @description= t('home.description')
  end
end

app/views/admin/home/index.html.erb
<div class="widget">
  <h3 class="section-title more-margin"><i class="icon-key"></i> <%=t('admin_zone.global.title')%></h3>
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#tab_users"><i class="icon-group"></i> <%=t('admin_zone.users.name')%></a></li>
    <li><a data-toggle="tab" href="#tab_proyects"><i class="icon-keyboard"></i> <%=t('admin_zone.proyects.name')%></a></li>
    <li><a data-toggle="tab" href="#tab_posts"><i class="icon-pencil"></i> <%=t('admin_zone.posts.name')%></a></li>
    <li><a data-toggle="tab" href="#tab_cvs"><i class="icon-eye-open"></i> <%=t('admin_zone.cvs.body')%></a></li>
    <li><a data-toggle="tab" href="#tab_comments"><i class="icon-comment-alt"></i> <%=t('admin_zone.comment.name')%></a></li>
  </ul>
  <div class="tab-content bottom-margin">

    <div id="tab_users" class="tab-pane active">
      <div class="shadowed-bottom">
        <div class="row">
          <div class="col-md-3 bordered">
            <div class="value-block padded-left text-center">
              <%=link_to t('common.edit')+' '+current_user.username,  edit_user_registration_path, class:"value-self" %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="tab_proyects" class="tab-pane">
      <div class="shadowed-bottom">
        <div class="row">
          <div class="col-xs-6 col-md-6 bordered">
            <div class="value-block padded-left text-center">
              <%=link_to t('admin_zone.proyects.list'),   admin_proyects_path , class:"value-self" %>
            </div>
          </div>
          <div class="col-xs-6 col-md-6 bordered">
            <div class="value-block padded-left text-center">
              <%=link_to t('admin_zone.proyects.new'),    new_admin_proyect_path  , class:"value-self" %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="tab_posts" class="tab-pane">
      <div class="shadowed-bottom">
        <div class="row">
          <div class="col-xs-6 col-md-6 bordered">
            <div class="value-block padded-left text-center">
              <%=link_to t('admin_zone.posts.list'), admin_posts_path, class:"value-self" %>
            </div>
          </div>
          <div class="col-xs-6 col-md-6 bordered">
            <div class="value-block padded-left text-center">
              <%=link_to t('admin_zone.posts.new'),  new_admin_post_path, class:"value-self" %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="tab_cvs" class="tab-pane">
      <div class="shadowed-bottom">
        <div class="row">
          <div class="col-md-3 bordered">
            <div class="value-block padded-left text-center">
              <%=link_to t('common.edit'),  edit_admin_cv_path(Cv.first), class:"value-self" %>
            </div>
          </div>
        </div>
      </div>
    </div>



    <div id="tab_comments" class="tab-pane">
      <div class="shadowed-bottom">
        <div class="row">
          <div class="col-xs-6 col-md-6 bordered">
            <div class="value-block padded-left text-center">
              <%=link_to t('admin_zone.comment.list'), admin_comments_path, class:"value-self" %>
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>
</div>