config/routes.rb
MarcosWeb::Application.routes.draw do
  root to: 'home#index'

  resources :proyects, only: [:index]
  resources :contacts, only: [:index,:create]
  resources :abouts, only: [:index]
  resources :blogs, only: [:index,:show] do
    resources :comments, only: [:create]
  end

  devise_for :users,skip: [:registrations,:passwords], path: "auth",
      path_names:
      { sign_in: 'login', sign_out: 'logout', password: 'secret',
        confirmation: 'verification', unlock: 'unblock',
        registration: 'register', sign_up: 'cmon_let_me_in'
      }
  as :user do
    get 'admin/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'admin/users' => 'devise/registrations#update', :as => 'user_registration'
  end



  namespace :admin do
    match 'home' =>'home#index',as: 'home', via: [:get]
    resources :proyects ,except: [:show] do
      resources :pphotos, only: [:create, :destroy]
    end
    resources :posts,except: [:show] do
      collection do
        post 'search' => 'posts#search', as: 'search'
        get 'sort/:by' => 'posts#sort', as: 'sort'
      end
    end
    resources :cvs,only: [:edit, :update]
    resources :comments,except: [:show, :new,:create] do
      collection do
        post 'search' => 'comments#search', as: 'search'
      end
    end


  end

end

app/models/proyect.rb
class Proyect < ActiveRecord::Base
  attr_accessible :name, :description,:sort_description, :media , :languague
  validates_presence_of :name,:description,:sort_description,:languague,:media

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :proyect_photos,dependent: :destroy

  PAGE=15
  PAGE_INDEX_PUBLIC=8
end

app/controllers/admin/proyects_controller.rb
class Admin::ProyectsController < ApplicationController
  authorize_resource class: false

  def index
    @proyects = Proyect.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proyects }
    end
  end

  def new
    @proyect = Proyect.new
    @load_javascript="run_rich_text_editor('es-ES');"
    respond_to do |format|
      format.html # new.html.erb.erb
      format.json { render json: @proyect }
    end
  end

  def edit
    @proyect = Proyect.find(params[:id])
    @proyect_photo = ProyectPhoto.new
    @proyect_photos= @proyect.proyect_photos
    @load_javascript="run_rich_text_editor('es-ES');"
  end

  def create
    @proyect = Proyect.new(params[:proyect])
    respond_to do |format|
      if @proyect.save
        format.html { redirect_to  edit_admin_proyect_path(@proyect), notice: t('activerecord.attributes.proyect.add') }
        format.json { render json: @proyect, status: :created, location: @proyect }
      else
        format.html { render action: "new" }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @proyect = Proyect.find(params[:id])
    respond_to do |format|
      if @proyect.update_attributes(params[:proyect])
        format.html { redirect_to admin_proyects_path, notice: t('activerecord.attributes.proyect.update') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @proyect = Proyect.find(params[:id])
    @proyect.destroy
    flash[:alert]= t('activerecord.attributes.proyect.remove')
    respond_to do |format|
      format.html { redirect_to  admin_proyects_path  }
      format.json { head :no_content }
    end
  end
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_filter :load_meta
  def index
    @proyects=Proyect.paginate(page: params[:page],order: 'created_at DESC', per_page: Proyect::PAGE_INDEX_PUBLIC)
    @load_javascript="colorbox_galleries(#{@proyects.count})"
  end


  private
  def load_meta
    @web_title= t('proyects.title')
    @description= t('proyects.description')
  end
end

app/views/admin/proyects/_edit_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_for(@proyect,:url => admin_proyect_path,html: { multipart: true }) do |f| %>
      <% if @proyect.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@proyect.errors.count, "error") %> <%=t('common.errors_form_wrapper')%>:</h2>
          <ul>
            <% @proyect.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%=f.label :name%>
            <%=f.text_field :name, class: 'form-control'%>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%=f.label :sort_description%>
            <%=f.text_field :sort_description, class: 'form-control'%>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%=f.label :description%>
        <%=f.cktext_area :description,size: '30x10' %>
      </div>

      <div class="form-group">
        <%= f.select :languague, get_kind_proyects,  prompt: t('activerecord.attributes.proyect.languague_prompt'),
                     class: 'form-control'%>
      </div>

      <div class="form-group">
        <%=f.label :media%> (Los enlaces de Dropbox deben tener la forma: https://dl.dropboxusercontent.com/s/6qw0tmhpyv0iukf/10_1CR.jpg)<br/>
        <%= image_tag @proyect.media%>
        <%=f.text_field :media, class: 'form-control'%>
      </div>

      <%= f.submit  t('common.edit'), class: 'btn btn-primary' %>

    <%end%>
  </div>


  <div class="col-md-6">
    <%= form_for(@proyect_photo,url: admin_proyect_pphotos_path(@proyect)) do |f| %>
        <%=f.label :media%> (Los enlaces de Dropbox deben tener la forma: https://dl.dropboxusercontent.com/s/6qw0tmhpyv0iukf/10_CR.jpg)<br/>
        <%=f.text_field :media, class: 'form-control'%>
      <%= f.submit t('activerecord.attributes.proyect_photo.submit'),class: 'btn btn-warning btn-round' %>
    <%end%>
    <br/>

    <%@proyect_photos.each do |photo|%>
      <div class="col-md-6">
        <a class="btn btn-danger btn-xs" data-method="delete" href="<%= admin_proyect_pphoto_path(@proyect,photo)%>"><i class="icon-remove"></i></a>
      <%= image_tag photo.media, class: 'col-md-12 '%>
      </div>
    <%end%>

  </div>
</div>

app/views/admin/proyects/_new_form.html.erb
<%= form_for(@proyect,:url => admin_proyects_path,html: { multipart: true }) do |f| %>
  <% if @proyect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proyect.errors.count, "error") %> <%=t('common.errors_form_wrapper')%>:</h2>
      <ul>
        <% @proyect.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%=f.label :name%>
        <%=f.text_field :name, class: 'form-control'%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%=f.label :sort_description%>
        <%=f.text_field :sort_description, class: 'form-control'%>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%=f.label :description%>
    <%=f.cktext_area :description,size: '30x10' %>
  </div>

  <div class="form-group">
    <%= f.select :languague, get_kind_proyects,  prompt: t('activerecord.attributes.proyect.languague_prompt'),
                 class: 'form-control'%>
  </div>

  <div class="form-group">
    <%=f.label :media%> (Los enlaces de Dropbox deben tener la forma: https://dl.dropboxusercontent.com/s/6qw0tmhpyv0iukf/10_1podemosCR.jpg)<br/>
    <%=f.text_field :media, class: 'form-control'%>
  </div>

  <%= f.submit  t('common.new'), class: 'btn btn-primary' %>

<%end%>

app/views/admin/proyects/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h3 class="form-title form-title-first"><i class="icon-terminal"></i> <%=t('admin_zone.proyects.edit')+': '+@proyect.name  %> </h3>
    <div class="widget">
      <div class="widget-content-white glossed">
        <div class="padded">
          <%= render 'edit_form' %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= link_to t('admin_zone.proyects.back'), admin_proyects_path, class: 'btn btn-default' %>

app/views/admin/proyects/index.html.erb
<h3 class="section-title more-margin"><i class="icon-keyboard"></i> <%=t('admin_zone.proyects.list')%></h3>
<%= link_to t('admin_zone.proyects.new'),   new_admin_proyect_path  %> |  <%=link_to t('admin_zone.global.title'), admin_home_path  %>
<div class="padded">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th><%=t('admin_zone.proyects.title')%></th>
      <th><%=t('admin_zone.proyects.languague')%></th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @proyects.each do |proyect| %>
    <tr>
      <td><%=proyect.name%></td>
      <td><%=proyect.languague%></td>
      <td><%= image_tag proyect.media, size: "200x150" %></td>
      <td class="text-right">
        <a class="btn btn-default btn-xs" href="<%=edit_admin_proyect_path(proyect)%>"><i class="icon-pencil"></i> edit</a>
        <a class="btn btn-danger btn-xs" data-method="delete" href="<%=admin_proyect_path(proyect)%>"><i class="icon-remove"></i></a>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/proyects/new.html.erb
<div class="row">
<div class="col-md-12">
  <h3 class="form-title form-title-first"><i class="icon-terminal"></i> <%=t('admin_zone.proyects.new')%></h3>
  <div class="widget">
    <div class="widget-content-white glossed">
      <div class="padded">
        <%= render 'new_form' %>
      </div>
    </div>
  </div>
</div>
</div>
<%= link_to t('admin_zone.proyects.back'), admin_proyects_path, class: 'btn btn-default' %>