config/routes.rb
MarcosWeb::Application.routes.draw do
  root to: 'home#index'

  resources :proyects, only: [:index]
  resources :contacts, only: [:index,:create]
  resources :abouts, only: [:index]
  resources :blogs, only: [:index,:show] do
    resources :comments, only: [:create]
  end

  devise_for :users,skip: [:registrations,:passwords], path: "auth",
      path_names:
      { sign_in: 'login', sign_out: 'logout', password: 'secret',
        confirmation: 'verification', unlock: 'unblock',
        registration: 'register', sign_up: 'cmon_let_me_in'
      }
  as :user do
    get 'admin/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'admin/users' => 'devise/registrations#update', :as => 'user_registration'
  end



  namespace :admin do
    match 'home' =>'home#index',as: 'home', via: [:get]
    resources :proyects ,except: [:show] do
      resources :pphotos, only: [:create, :destroy]
    end
    resources :posts,except: [:show] do
      collection do
        post 'search' => 'posts#search', as: 'search'
        get 'sort/:by' => 'posts#sort', as: 'sort'
      end
    end
    resources :cvs,only: [:edit, :update]
    resources :comments,except: [:show, :new,:create] do
      collection do
        post 'search' => 'comments#search', as: 'search'
      end
    end


  end

end

app/views/layouts/_header.html.erb
<a href="<%=root_path%>" <%=set_active_home%>><i class="icon-home" ></i> <%=t('navbar.index')%></a>
<a href="<%= proyects_path%>" <%=set_active_proyects%>><i class=" icon-magic"></i> <%=t('navbar.proyects')%></a>
<a href="<%= blogs_path %>" <%=set_active_blog%>><i class="icon-comments"></i> <%=t('navbar.blog')%></a>
<a href="<%= abouts_path %>" <%=set_active_about_me%>><i class="icon-eye-open"></i> <%=t('navbar.about')%></a>
<a href="<%= contacts_path %>" <%=set_active_contact%>><i class=" icon-pencil"></i> <%=t('navbar.contact')%></a>

<%if user_signed_in?%>
<%= link_to '<i class="icon-signout"></i>'.html_safe, destroy_user_session_path, :method => :delete %>
<%= link_to '<i class="icon-wrench"></i>'.html_safe, admin_home_path%>
<%else%>
<a href="<%= user_session_path  %>"><i class="icon-gear"></i></a>
<%end%>

app/views/layouts/_social_share.html.erb
<div class="text-center">
  <a href="http://twitter.com/home?status=<%=request.original_url%>" title="Share on Twitter" target="_blank" class="btn btn-default btn-round"><i class="icon-twitter"></i> Twitter</a>
  <!-- Facebook -->
  <a href="https://www.facebook.com/sharer/sharer.php?u=<%=request.original_url%>" class="btn btn-default btn-round"><i class="icon-facebook"></i> Facebook</a>
  <!-- LinkedIn -->
  <a href="http://www.linkedin.com/shareArticle?mini=true&url=<%=request.original_url%>&title=<%=@web_title%>&summary=<%=@description%>" title="Share on LinkedIn" target="_blank" class="btn btn-default btn-round"><i class="icon-linkedin"></i> LinkedIn</a>
  <!-- Whatsapp-->
  <a href="whatsapp://send?text=<%=request.original_url%>" title="Share on Whatsapp" data-action="share/whatsapp/share" class="btn btn-default btn-round"><%=icon('whatsapp',class: 'strong')%> Whatsapp</a>
  <!-- Telegram-->
  <a href="tg://msg?text=<%=request.original_url%>" title="Share on Telegram" class="btn btn-default btn-round"><%=icon('paper-plane',class: 'strong')%> Telegram</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @web_title %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/assets/linux.ico">
  <link href='http://fonts.googleapis.com/css?family=Oswald:300,400,700|Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <% if params[:controller] == 'home' %>
      <link href="http://fonts.googleapis.com/css?family=Lobster:400" rel="stylesheet" type="text/css">
  <% end %>
  <meta http-equiv="content-language" content="es-ES">
  <meta name="distribution" content="global"/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="<%= @description %>">
  <meta name="Keywords" content="Marcos Martin Garcia-Muñoz, Informática, Ruby on Rails, Ror, Java, C++, Ingeniero, Html, Css, Photoshop ">
  <meta http-equiv="content-type" content="text/html;charset=UTF-8">
  <!-- Facebook metas -->
  <meta property="og:title" content="<%= @web_title %>"/>
  <meta property="og:description" content="<%= @description_fb %>"/>
  <meta property="og:url" content="<%= @url %>"/>
  <meta property="og:image" content="<%= @url %><%= @image %>"/>
  <meta property="og:type" content="website"/>
  <!-- Facebook metas -->
  <!-- Twitter metas -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="<%= @web_title %>">
  <meta name="twitter:description" content="<%= @description_fb %>">
  <meta name="twitter:image:src" content="<%= @url %><%= @image %>">
  <!-- Twitter metas -->
  <!-- Bing Meta -->
  <meta name="msvalidate.01" content="009FDB6A4BB3FC6EF9B2FF64126D93AB"/>
  <!-- Bing Meta -->
</head>
<body
<% unless @load_javascript.nil? %>onload="<%= @load_javascript %>"
<% end %>>
<div class="all-wrapper">
  <div class="row">
    <div class="col-md-12">
      <div class="content-wrapper wood-wrapper">
        <div class="row">
          <div class="col-xs-12" align="center">
            <%= link_to(image_tag('milogo.png'), '/') %>
          </div>
        </div>
        <div class="content-inner">
          <div class="page-header">
            <div class="header-links">
              <%= render 'layouts/header' %>
            </div>
            <h1 class="remove_uppercase">MarcosMartinGm.es</h1>
          </div>
          <div class="main-content">
            <% if notice.present? %>
                <div class="alert alert-success alert-dismissable">
                  <i class="icon-thumbs-up"></i>
                  <strong><%= t('common.info') %></strong>
                  <%= notice.html_safe %>
                  <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
                </div>
            <% end %>
            <% if alert.present? %>
                <div class="alert alert-danger alert-dismissable">
                  <i class="icon-warning-sign"></i>
                  <strong><%= t('common.danger') %></strong>
                  <%= alert.html_safe %>
                  <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
                </div>
            <% end %>
            <%= yield %>
          </div>
        </div>
        <footer>
          <br>

          <div class="row">
            <div class="col-xs-12 col-md-4">
              Diseño y programación:<br/>
              <%= mail_to "marcos.martingm@gmail.com", '<i class="icon-envelope"></i>'.html_safe+"Marcos Martín García-Muñoz", class: "btn btn-default btn-round" %>
            </div>

            <div class="col-xs-12 col-md-4 ">
              Código fuente:<br/>
              <%= link_to image_tag('Bitbucket_Logo.png'), "https://bitbucket.org/Marcos_Martin/marcos_web", class: "btn btn-default btn-round" %><br/>
              <%= link_to(image_tag('rails3.png'), 'http://rubyonrails.org/', class: "thumbnail col-xs-2 col-md-2") %>
              <%= link_to(image_tag('html5.png'), 'http://es.wikipedia.org/wiki/HTML5', class: "thumbnail col-xs-2 col-md-2") %>
              <%= link_to(image_tag('css3.png'), 'http://www.w3.org/Style/CSS/current-work', class: "thumbnail col-xs-2 col-md-2") %>
              <%= link_to(image_tag('js.png'), 'http://es.wikipedia.org/wiki/JavaScript', class: "thumbnail col-xs-2 col-md-2") %>
              <%= link_to(image_tag('bootstrap3.png'), 'http://getbootstrap.com/', class: "thumbnail col-xs-2 col-md-2") %>

            </div>

            <div class="col-xs-12 col-md-4 ">
              <%=t('common.share').upcase%>:<br/>
              <%=render 'layouts/social_share'%>
            </div>
          </div>
          <div class="row col-xs-12 col-md-12">
            <%= link_to image_tag('creativecommons4.png'), "http://creativecommons.org/licenses/by/4.0/", class: "btn" %>
            Marcos Martin Web. Creative Commons Reconocimiento 4.0 Internacional License.
          </div>

        </footer>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-47284940-1']);
    _gaq.push(['_setDomainName', '.af.cm']);
    _gaq.push(['_trackPageview']);

    (function () {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
    })();

</script>
</body>
</html>